### PR TITLE
Added support for Monarch HD, Monarch LCS and Datavideo NVS-30

### PR DESCRIPTION
**Pull request by bbredewold**
In this pull request I've added support for the Monarch HD, Monarch LCS and Datavideo NVS-30. Also implemented the parsing of the response and adding the status of the devices into variables.

### CODE REVIEW

**Comment by bbredewold** [comment]
@bevanjkay Do you have the time to test this module for your Monarch HDX?

**Comment by bevanjkay** [comment]
Hi @bbredewold - I am away for a few days, but should hopefully be able to have a look this time next week.

**Comment by bbredewold** [comment]
> Hi @bbredewold - I am away for a few days, but should hopefully be able to have a look this time next week.

@bevanjkay That would be great. If it works on my HD and your HDX we can safely assume it will work for the LCS model too.
Looking forward to the testresults!

**Comment by bevanjkay** [comment]
@bbredewold oh, I do only have the Monarch HD

**Comment by bbredewold** [comment]
> @bbredewold oh, I do only have the Monarch HD

@bevanjkay No problem, I have the NVS-30 to test with.

**Comment by bbredewold** [comment]
Alright, my testing is done. All seems to work fine.
Only thing was that the Interval didn't get cleared on destroy, which I added now.

**Comment by bevanjkay** [comment]
@bbredewold Sorry that I didn't get a chance to test the module before I went on leave. I'm away from my Monarch for another week and a half.

**Comment by krocheck** [comment]
@bbredewold this needs some error handling.

- `sendCommand(actionName) {}` is firing unhandled promise rejections.  We need some try-catch or .catch inside

**Pull request merged**
